#!/usr/bin/env python3
"""Run end-to-end carving tests and generate a markdown test report."""

from __future__ import annotations
from datetime import datetime

import json
import shutil
import sys
from pathlib import Path
from typing import Dict, List

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from carving_tool import carve_file
from signatures import get_all_signatures


def format_status(passed: bool) -> str:
    return "PASS" if passed else "FAIL"


def main() -> int:
    root = Path(__file__).resolve().parent
    test_data_dir = root / "test_data"
    manifest_path = test_data_dir / "expected_manifest.json"
    
    timestamp = datetime.now().strftime("%m_%d_%Y_%H_%M_%S")
    test_output_root = root / "test_output"
    test_output_root.mkdir(parents=True, exist_ok=True)
    output_root = test_output_root / timestamp

    if not manifest_path.exists():
        print("Manifest not found. Run generate_test_files.py first.")
        return 1

    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    signatures = get_all_signatures()

    if output_root.exists():
        shutil.rmtree(output_root)
    output_root.mkdir(parents=True, exist_ok=True)

    # Compare expected carve hashes from manifest against fresh carve results.
    rows: List[Dict[str, object]] = []
    all_passed = True

    for case in manifest["cases"]:
        file_name = str(case["file"])
        expected_carved = case["carved_by_type"]
        target_file = test_data_dir / file_name
        case_output_dir = output_root / f"{Path(file_name).stem}_output"

        results = carve_file(
            target_path=target_file,
            signatures=signatures,
            output_dir=case_output_dir,
            prefix="carved",
        )

        actual_carved: Dict[str, List[str]] = {}
        for result in results:
            ftype = result.file_type
            if ftype not in actual_carved:
                actual_carved[ftype] = []
            actual_carved[ftype].append(result.sha256)

        passed = True
        for sig_name, expected_info in expected_carved.items():
            expected_hashes = expected_info["sha256"]
            actual_hashes = actual_carved.get(sig_name, [])
            if expected_hashes != actual_hashes:
                passed = False
                break
        if set(actual_carved.keys()) != set(expected_carved.keys()):
            passed = False
        
        all_passed = all_passed and passed

        expected_str = ", ".join(
            f"{ft}({exp_info['count']})"
            for ft, exp_info in expected_carved.items()
        ) or "none"
        actual_str = ", ".join(
            f"{ft}({len(hashes)})" for ft, hashes in actual_carved.items()
        ) or "none"

        rows.append(
            {
                "file": file_name,
                "description": str(case["description"]),
                "expected": expected_str,
                "actual": actual_str,
                "status": format_status(passed),
            }
        )

        print(
            f"[{format_status(passed)}] {file_name}: expected={expected_str}, actual={actual_str}"
        )

    report_path = output_root / "test_summary.md"

    # Build a human-readable summary for quick regression review.
    lines: List[str] = []
    lines.append("# Test Summary")
    lines.append("")
    lines.append("## How test files were created")
    lines.append(
        "Test files are generated by `test/generate_test_files.py`, which:"
    )
    lines.append("")
    lines.append("1. Loads real files from `test/test_data_source/`")
    lines.append("2. Embeds files in random binary padding data")
    lines.append("3. Wraps each file with registered binary signatures:")
    lines.append(f"   - PNG header: `{manifest['signatures']['png']['header_hex']}`")
    lines.append(f"   - PNG footer: `{manifest['signatures']['png']['footer_hex']}`")
    lines.append("4. Adds low-frequency false headers/footers to simulate real-world scenarios")
    lines.append("5. Records expected carving results in a manifest JSON file")
    lines.append("")
    lines.append("The random binary padding ensures realistic test conditions and demonstrates the carver's robustness.")
    lines.append("")
    lines.append("## File type signatures")
    lines.append("")
    for file_type, sig_info in manifest["signatures"].items():
        lines.append(f"### {file_type.upper()}: {sig_info['description']}")
        lines.append(f"- Header: `{sig_info['header_hex']}`")
        lines.append(f"- Footer: `{sig_info['footer_hex']}`")
        lines.append("")
    lines.append("## Test files used")
    lines.append("")
    for case in manifest["cases"]:
        lines.append(f"- `{case['file']}`: {case['description']}")
    lines.append("")
    lines.append("## Test results")
    lines.append("| File | Expected carving | Actual carving | Status |")
    lines.append("|---|---|---|---|")
    for row in rows:
        lines.append(
            f"| `{row['file']}` | {row['expected']} | {row['actual']} | {row['status']} |"
        )
    lines.append("")
    lines.append(f"Overall result: **{format_status(all_passed)}**")

    report_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Report written to: {report_path}")

    return 0 if all_passed else 1


if __name__ == "__main__":
    raise SystemExit(main())
